.\" Process this file with
.\" groff -man -Tascii extract.1
.\"
.TH TWOPENCE_EXTRACT "1" "@DATE@" "Twopence @VERSION@" "User Commands"

.SH NAME
twopence_extract \- extract a test result

.SH SYNOPSIS
.B twopence_extract [
.I OPTION
.B ]... 
.I TARGET
.B  
.I REMOTE
.B  
.I LOCAL

.SH DESCRIPTION
.B twopence_extract
extracts a remote file from the system under test (SUT).
.PP
The SUT can be accessed by any means provided by Twopence:
virtio (for QEmu/KVM virtual machines), ssh, or serial
(with a null-modem cable). This access method and the exact
location of the SUT are defined by the
.I TARGET
parameter. With the virtio and serial methods, the program
.B twopence_test_server
must be installed and running on the SUT. With the ssh method,
a SSH server must be installed and running on the SUT.
.PP
The transfer can be done as any local user on the SUT (default is
.I root
user). There is absolutely no access control, so make sure you
use Twopence only on test machines on which you have exclusive
access.

.SH OPTIONS
.IP \fB\-u\fR\ \fIUSERNAME\fR
.IP\fB\-\-user\fR=\fIUSERNAME\fR
Define the username under which the file is read
on the system under test.
.IP \fB\-v\fR
.IP \fB\-\-version\fR
Display version information.
.IP \fB\-h\fR
.IP \fB\-\-help\fR
Display a short error message.
.PP
.I TARGET
obeys the following syntax:
.PP
.IP \fBvirtio:\fR\fISOCKETNAME\fR
for the access through virtio to
a QEmu/KVM virtual machine. \fISOCKETNAME\fR is the filename of
the UNIX domain socket used by the virtio channel. It can be defined
for example with help of
.BR virt-manager (5)
command.
.PP
.IP \fBssh:\fR\fIHOSTNAME\fR|\fIIPADDRESS\fR\fB[:\fR\fIPORTNUMBER\fR\fB]\fR
for the access though SSH to a remote host.
.PP
.IP \fBserial:\fR\fIDEVICENAME\fR
for the access through a serial port. \fIDEVICENAME\fR is the filename
of a UNIX character device describing the serial port.
.PP
.I REMOTE
is the filename of the file to send from the SUT.
.PP
.I LOCAL
is the filename of the location where to write the received file.

.SH EXAMPLES
Example syntax for the virtio access method:
.IP \fBtwopence_extract\ \-u\ johndoe\ virtio:/tmp/sut.sock\ remote_file.txt\ local_file.txt\fR
it will use
.I /tmp/sut.sock
to communicate with the QEmu/KVM host.
.PP
Example syntax for the ssh access method:
.IP \fBtwopence_extract\ \-\-user=johndoe\ ssh:host.example.com\ remote_file.txt\ local_file.txt\fR
it is functionally equivalent to
\fBscp\ johndoe@host.example.com:remote_file.txt\ local_file.txt\fR
without server footprint verification.
.PP
Example syntax for the serial access method:
.IP \fBtwopence_command\ serial:/dev/ttyS0\ remote_file.txt\ local_file.txt\fR

.SH BUGS
Do not expect any security from Twopence. Use with care. You've been warned.
.PP
For the moment, only one session with the remote host can be used at
a time.
.PP
For the moment, it is not possible to use jokers like * or ? to transfer
several files at once. It is also not possible to transfer recursively a
whole directory.

.SH AUTHOR
The Twopence developpers at SUSE Linux.

.SH SEE ALSO
.BR twopence_command (1),
.BR twopence_inject (1),
.BR twopence_exit (1),
other shell commands to access the System Under Test.
.PP
.BR twopence_test_server (1),
the server to be installed on the System Under Test when using
the virtio or serial access methods.
