#!/bin/bash
#
# Run a test script against a virtio target.
#

myname=`readlink -f $0`
TOPDIR=${myname%/tests/*}

SCRIPT=$1; shift
if [ -z "$SCRIPT" ]; then
	echo "$0: you have to specify a test script as argument" >&2
	exit 1;
fi

if [ ! -x "$SCRIPT" ]; then
	echo "$0: test scrpt \"$SCRIPT\" does not exist or is not executable" >&2
	exit 1
fi

export LD_LIBRARY_PATH=$TOPDIR/library
export PYTHONPATH=$TOPDIR/python


# First, start the test server
cat <<EOF
------------------------------------------------------------------
--- Starting test server ---

EOF
../server/twopence_test_server --daemon --port-unix /tmp/twopence.sock $TWOPENCE_SERVER_OPTIONS

cat <<EOF
------------------------------------------------------------------
--- Running $SCRIPT virtio:/tmp/twopence.sock ---

EOF

$SCRIPT virtio:/tmp/twopence.sock
status=$?

cat <<EOF

--- Exit status $status ---
------------------------------------------------------------------
EOF

if [ $status -ne 0 ]; then
	echo "Test script failed (status=$status)" >&2
	echo "Server log file can be found in server.log" >&2
fi

killall -TERM twopence_test_server
if [ $? -ne 0 ]; then
	echo "Server exited with status $?" >&2
fi

exit $status
