.PHONY: all install clean

all:

install:
	mkdir -p $(DESTDIR)/usr/lib/twopence-0
	cp example.sh $(DESTDIR)/usr/lib/twopence-0
	cp example.rb $(DESTDIR)/usr/lib/twopence-0
	cp example.py $(DESTDIR)/usr/lib/twopence-0

clean:

