.PHONY: all install clean

all:

install:
	mkdir -p $(DESTDIR)/usr/lib/twopence-0
	cp test.sh $(DESTDIR)/usr/lib/twopence-0
	cp test.rb $(DESTDIR)/usr/lib/twopence-0
	cp test.py $(DESTDIR)/usr/lib/twopence-0

clean:

